# meta-yadiggg/conf/layer.conf
# We have a packages directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-yadiggg"
BBFILE_PATTERN_meta-yadiggg = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-yadiggg = "9"

LAYERSERIES_COMPAT_meta-yadiggg = "scarthgap"

# Enforce immediate build dependency on Freescale and OpenEmbedded core
LAYERDEPENDS_meta-yadiggg = "core freescale-layer openembedded-layer"
