#!/bin/sh
### BEGIN INIT INFO
# Provides:          yadiggg-init
# Required-Start:    $syslog $local_fs
# Required-Stop:     $syslog $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start yadiggg Sonic ID daemon on boot
### END INIT INFO

DAEMON=/usr/bin/yadiggg_capture
NAME=yadiggg_capture
DESC="Sonic ID Capture Daemon"

test -x $DAEMON || exit 0

case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon --start --quiet --background --exec $DAEMON
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --stop --quiet --oknodo --exec $DAEMON
	echo "$NAME."
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "
	start-stop-daemon --stop --quiet --oknodo --retry 30 --exec $DAEMON
	start-stop-daemon --start --quiet --background --exec $DAEMON
	echo "$NAME."
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
